import { AuthProvider } from "@/providers/auth-provider";
import QueryProviders from "@/providers/query-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProviders>
            <AuthProvider>{children}</AuthProvider>
          </QueryProviders>
        </ThemeProvider>
        <Toaster
          expand
          toastOptions={{
            className: "!font-medium !bg-background !border-secondary/30", // applies to all
            classNames: {
              loading: "!text-foreground",
              success: "!text-green-500/80",
              error: "!text-destructive",
              info: "!text-blue-500",
              warning: "!text-yellow-500",
            },
          }}
        />
      </body>
    </html>
  );
}
